version: "3"
services:
  nginx:
    restart: always
    build: ./dockers/nginx
    ports:
      - 80:80
    depends_on:
      - rails
      - react
      - gitlab
    links:
      - rails
      - react
      - gitlab
  rails:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    expose:
      - 3000
  react:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    expose:
      - 8080
  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    hostname: resivalex
    domainname: gitlab.resivalex.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.resivalex.com'
    expose:
      - '80:80'
      - '22:22'
      - '443:443'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
