version: "3"
services:
  nginx:
    restart: always
    build: ./dockers/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails
      - react
    links:
      - rails
      - react
    volumes:
      - /etc/infrastructure/certbot/conf:/etc/letsencrypt
      - /etc/infrastructure/certbot/www:/var/www/certbot
  rails:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    expose:
      - 3000
  react:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    expose:
      - 8080
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - /etc/infrastructure/certbot/conf:/etc/letsencrypt
      - /etc/infrastructure/certbot/www:/var/www/certbot
