version: "3"
services:
  nginx:
    restart: always
    build: ./dockers/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails
      - react
    volumes:
      - /etc/infrastructure/certificates:/var/www/certificates
    network_mode: host
  rails:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    ports:
      - 3000:3000
  react:
    restart: always
    build:
      context: ../react-blog
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    ports:
      - 8080:8080
  acme:
    image: neilpang/acme.sh
    command: daemon
    volumes:
      - /etc/infrastructure/certificates:/acme.sh
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - /etc/infrastructure/strapi:/srv/app
    ports:
      - 1337:1337
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - /etc/infrastructure/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
