version: "3"
services:
  nginx:
    build: ./dockers/nginx
    ports:
      - 80:80
    depends_on:
      - rails
      - react
      - gitlab
    links:
      - rails
      - react
      - gitlab
  rails:
    build:
      context: ../react-blog
      dockerfile: ./dockers/rails/Dockerfile
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=rio32pqir23r2h3ur23prh2u13r213r
    command: rails s
    expose:
      - 3000
  react:
    build:
      context: ../react-blog
      dockerfile: ./dockers/react/Dockerfile
    command: node server.js
    expose:
      - 8080
  gitlab:
    image: gitlab/gitlab-ee:latest
    expose:
      - 80
      - 22
      - 443
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
