version: "3"
services:
  nginx:
    restart: always
    build: ./dockers/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/infrastructure/certificates:/var/www/certificates
    network_mode: host
  acme:
    image: neilpang/acme.sh
    command: daemon
    volumes:
      - /etc/infrastructure/certificates:/acme.sh
